POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "testimies",
    "number": "6969420420"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "as",
    "number": "6969"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "6969420420"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": ""
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "6969420420"
}

###

POST https://puhelinluettelojaakko.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "testimies",
    "number": "6969420420"
}

###

POST https://puhelinluettelojaakko.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "6969420420"
}

###

POST https://puhelinluettelojaakko.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "6969420420"
}